// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
} from "dedot/contracts";

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x32e1716b0d271587c25554c4dba829561bc5c64089463939452c0d4333fee56d
   **/
  ProposalSubmitted: GenericContractEvent<
    "ProposalSubmitted",
    {
      /**
       *
       * @indexed: false
       **/
      bidder: AccountId32;
      /**
       *
       * @indexed: false
       **/
      value: string;
    }
  >;

  /**
   *
   * @signature_topic: 0x77a62dba59a499af3114840a01533c425e5092dc1abaacdb872a53ba03a8a181
   **/
  Won: GenericContractEvent<
    "Won",
    {
      /**
       * The winner.
       *
       * @indexed: false
       **/
      winner: AccountId32;
      /**
       * The winning amount.
       *
       * @indexed: false
       **/
      amount: bigint;
    }
  >;
}
