// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32Like } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {string} url
   * @param {ContractTxOptions} options
   *
   * @selector 0xc4d32d79
   **/
  submitProposal: GenericContractTxCall<
    ChainApi,
    (
      url: string,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {AccountId32Like} winnerId
   * @param {ContractTxOptions} options
   *
   * @selector 0x52fd3e2d
   **/
  pickBidder: GenericContractTxCall<
    ChainApi,
    (
      winnerId: AccountId32Like,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x6dbac0f5
   **/
  startBiddingForGrant: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x51798d6e
   **/
  stopBiddingForGrant: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
